name: Deployment
on: [push, workflow_dispatch]
concurrency: 
  group: plogon-deploy
  cancel-in-progress: true

jobs:
  run-plogon:
    name: Build Plugins
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout manifests
      uses: actions/checkout@v3
      with:
        repository: KangDohwa/PluginDistD17KR
        path: manifests
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout Plogon
      uses: actions/checkout@v3
      with:
        repository: KangDohwa/Plogon
        #ref: V1.0.6
        path: Plogon
        
    - name: Checkout Dist
      uses: actions/checkout@v3
      with:
        repository: KangDohwa/PluginDistD17KR
        path: output
        ssh-key: ${{ secrets.DIST_SSH_KEY }}
        persist-credentials: true
        ref: main

    - name: Create required folders
      run: |
        mkdir artifacts
        mkdir work
        
    - name: Cache docker image
      uses: actions/cache@v3
      env:
        cache-name: ${{ secrets.EXTENDED_IMAGE_LINK }}
      with:
        path: ~/.plogon_cache
        key: cache-${{ env.cache-name }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugin-artifact
        path: artifacts
        
    - name: Commit files
      continue-on-error: true
      run: |
        cd ${{ github.workspace }}/output
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update distribute"
        ${{ github.workspace }}
        
    - name: Push plugin dist
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: output
        repository: KangDohwa/PluginDistD17KR
        ssh: true
